apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533267042370:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-nC4gOYDlrBE6
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::533267042370:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-16T12:48:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2413"
  uid: 02c86ece-6120-4ca8-beb0-1b1b9dc254ac
